### ISSUE TITLE
План работ

### ISSUE THREAD

**Issue by torero-vlg** [torero-vlg/gis#21]
- [ ] 1. реструктуризация обобщенных данных по ЗП, кадастровому участку, культуре. Доработка Olap.
- [x] 2. выгрузить данные из росреестра по списку кадастровых участков
- [x] 3. парсинг  файлов росреестра  #24 
- [x] 4. выгрузка реструктуризированных данных для заливки в гис (в формате sql) #27
- [x] 5. добавить свойство ЗП (наш/не наш) : в  БД, на форму (фильтр)  #22 **готово**
- [ ] 6. вывод участков и маркеров сразу, раскраска по ЗП или/и по признаку наш/не наш. визуальное отображение с/х только во всплывающем окне или пункт 7. #26  #29 
- [ ] 7. изучить возможности библиотек для отображения с/х культур маркерами
